name: Build and Publish

on:
  push:
    tags: []

jobs:
  publish:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    - uses: abatilo/actions-poetry@v2
    - run: poetry config pypi-token.pypi ${{secrets.PYPI}}
    - run: poetry install
    - run: poetry build
    - run: poetry publish
    - uses: actions/upload-artifact@v4
      with:
        name: wheel
        path: ${{github.workspace}}/dist/*.whl
  
  release:
    runs-on: ubuntu-latest
    needs: [publish]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: wheel
          path: ${{github.workspace}}/dist
      - name: Release
        uses: docker://antonyurchenko/git-release:v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ALLOW_EMPTY_CHANGELOG: true
        with:
          args: dist/*
